language: node_js

node_js:
  - "5.0"

# Use container-based Travis infrastructure.
sudo: false

addons:
  ssh_known_hosts:
  - 192.241.218.94

branches:
  only:
    - master

before_install:
  # GUI for real browsers.
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

  # Decrypt the key file
  - openssl aes-256-cbc -K $encrypted_94338e915bdd_key -iv $encrypted_94338e915bdd_iv
    -in deploy_static.pem.enc -out deploy_static.pem -d

install:
  - npm install

script:
  - npm test
  - NODE_ENV=production node_modules/.bin/builder run build-static

# Once build on Travis is working, automatically deploy it on master only:
after_success:
  if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    - chmod 600 deploy_static.pem
    - ssh -i deploy_static.pem formidable@192.241.218.94 "rm -rf static/victory-docs-staging && mkdir static/victory-docs-staging"
    - scp -i deploy_static.pem -rp ./build/* formidable@192.241.218.94:/home/formidable/static/victory-docs-staging
    - ssh -i deploy_static.pem formidable@192.241.218.94 "rm -rf static/victory && mv static/victory-docs-staging/ static/victory"
    echo "DEPLOYED."
  else
    echo "This will not deploy."
  fi
