language: node_js

node_js:
  - "5.0"

# Use container-based Travis infrastructure.
sudo: false

branches:
  only:
    - task-deployAllTheThings

addons:
  ssh_known_hosts:
    - 192.241.218.94

install:
  - npm install

script:
  - npm test

  # run webpack, copy assets to /build folder
  - NODE_ENV=production builder run build-static

after_success:
  - eval "$(ssh-agent -s)" # start the ssh-agent
  - chmod 600 .travis/deploy_key.pem # this key should have push access
  - ssh-add .travis/deploy_key.pem
  - scp -rp ./build/* formidable@192.241.218.94:/home/formidable/static/test
