language: node_js

node_js:
  - "5.0"

# Use container-based Travis infrastructure.
sudo: false

branches:
  only:
    - task-deployAllTheThings

before_install:
  - openssl aes-256-cbc -K $encrypted_94338e915bdd_key -iv $encrypted_94338e915bdd_iv
    -in deploy_static.pem.enc -out deploy_static.pem -d

install:
  - npm install

script:
  - npm test
  - NODE_ENV=production builder run build-static

after_success:
  - scp --keyfile deploy_static.pem -rp ./build/* formidable@192.241.218.94:/home/formidable/static/test
