language: node_js

node_js:
  - "5.0"

# Use container-based Travis infrastructure.
sudo: false

branches:
  only:
    - task-deployAllTheThings

addons:
  ssh_known_hosts:
    - 192.241.218.94

install:
  - npm install

script:
  - npm test

  # run webpack, copy assets to /build folder
  - builder run build-static
