language: node_js

node_js:
  - "5.0"

# Use container-based Travis infrastructure.
sudo: false

branches:
  only:
    - task-deployAllTheThings

install:
  - npm install

script:
  - npm test

  # run webpack, copy assets to /build folder
  - builder run build-static
